"""San Diego County — different portal, same Accela engine."""

CONFIGS = {
    'san_diego_residential': {
        'name':               'San Diego',
        'base_url':           'https://publicservices.sandiegocounty.gov/CitizenAccess',
        'portal_url':         'https://publicservices.sandiegocounty.gov/CitizenAccess/Default.aspx',
        'module':             'Building',
        'permit_type':        'Residential Alteration or Addition',
        'use_project_name':   'otc',
        'source':             'san_diego_accela',
        'lead_category':      'residential',
        'daily_only':         True,
        'owner_from_contacts': True,
        'col_date':           1,
        'col_permit_num':     None,
        'col_permit_type':    3,
        'col_description':    4,
        'col_project_name':   5,
        'col_status':         6,
        'col_short_notes':    8,
        'col_address':        9,
    },
    'san_diego_commercial': {
        'name':               'San Diego',
        'base_url':           'https://publicservices.sandiegocounty.gov/CitizenAccess',
        'portal_url':         'https://publicservices.sandiegocounty.gov/CitizenAccess/Default.aspx',
        'module':             'Building',
        'permit_type':        'Commercial Alteration or Addition',
        'use_project_name':   None,
        'source':             'san_diego_accela',
        'lead_category':      'commercial',
        'daily_only':         True,
        'short_notes_filter': '8004',
        'owner_from_contacts': True,
        'col_date':           1,
        'col_permit_num':     None,
        'col_permit_type':    3,
        'col_description':    4,
        'col_project_name':   5,
        'col_status':         6,
        'col_short_notes':    8,
        'col_address':        9,
    },
}
